name: Build and publish image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build with nix-build
        run: nix-build nix-base.nix

      - name: Load Docker image
        run: docker load -i result

      - name: Build Docker image
        run: docker build -t nix-env:latest -f Dockerfile .

      - name: Login to Docker
        run: docker login -u $({ secrets.DOCKER_USERNAME }) -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag nix-env:latest haskelious/nix-env:latest

      - name: Push Docker image
        run: docker push haskelious/nix-env:latest
